/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bauer' at '17-1-1 下午12:53' with Gradle 3.2.1
 *
 * @author bauer, @date 17-1-1 下午12:53
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
